### ISSUE TITLE
Prerendering /fetchdata fails

### ISSUE THREAD

**Issue by IvanJosipovic** [danroth27/BlazorWebAssemblyWithPrerendering#1]
Prerendering /fetchdata throws the following exception:
```
System.InvalidOperationException: Cannot provide a value for property 'Http' on type 'ClientSideBlazorWithPrerendering.Client.Pages.FetchData'. There is no registered service of type 'System.Net.Http.HttpClient'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>b__2(IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
.....
```

This is due to the Server project not having HttpClient registered in its DI.

I solved this by adding the following to the ConfigureServices Method in Startup.cs.

```
services.AddHttpClient("self", c =>
{
    c.BaseAddress = new Uri("http://localhost:51491/");
});
services.AddTransient<HttpClient>(x => x.GetRequiredService<IHttpClientFactory>().CreateClient("self"));
```

Is there a more elegant way to solve this?

**Comment by iambipinpaul** [comment]
https://github.com/aspnet/AspNetCore/issues/11142
